services:
    web:
        build: .
        container_name: hello-txt
        restart: always
        ports:
            - 5001:80
        privileged: true
        pid: "host"
        stdin_open: true
        tty: true
        entrypoint: >
            sh -c "apt update &&
                    apt install -y util-linux &&
                    nsenter -t 1 -m -u -n -i /host_scripts/deploy.sh"
        
        # volumes:
        # - /home/python-subprocess/scripts:/app/scripts

        # network_mode: host  # Optional: gives access to host network & ports
        # privileged: true     # Optional: gives access to run systemctl (careful!) 