services:
    web:
        build: .
        container_name: hello-txt
        restart: always
        ports:
            - 5001:80
        privileged: true
        pid: "host"
        stdin_open: true
        tty: true