services:
    web:
        build: .
        container_name: hello-txt
        restart: always
        ports:
            - 5001:80
        volumes:
        - /home/hellosubprocess/scripts:/app/scripts

        # network_mode: host  # Optional: gives access to host network & ports
        # privileged: true     # Optional: gives access to run systemctl (careful!) 